# Generated by Django 5.2.17 on 2026-08-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateField(unique=True)),
                ('peak_kwh', models.FloatField()),
                ('offpeak_kwh', models.FloatField()),
                ('net_kwh', models.FloatField()),
                ('nem_charges', models.FloatField()),
            ],
            options={
                'ordering': ['end_date'],
            },
        ),
        migrations.CreateModel(
            name='GasBillPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(unique=True)),
                ('therms', models.FloatField()),
                ('charges', models.FloatField()),
            ],
            options={
                'ordering': ['end_date'],
            },
        ),
    ]
