# Generated by Django 5.2.17 on 2026-10-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CcaAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('summer', 'Summer'), ('winter', 'Winter')], max_length=6)),
                ('period', models.CharField(choices=[('peak', 'Peak'), ('offpeak', 'Offpeak')], max_length=7)),
                ('effective_from', models.DateField()),
                ('amount', models.FloatField()),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['effective_from', 'season', 'period'],
                'constraints': [models.UniqueConstraint(fields=('season', 'period', 'effective_from'), name='uniq_cca_adjustment')],
            },
        ),
        migrations.CreateModel(
            name='UtilityRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('summer', 'Summer'), ('winter', 'Winter')], max_length=6)),
                ('period', models.CharField(choices=[('peak', 'Peak'), ('offpeak', 'Offpeak')], max_length=7)),
                ('tier', models.PositiveSmallIntegerField(default=1)),
                ('effective_from', models.DateField()),
                ('rate', models.FloatField()),
                ('source', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['effective_from', 'season', 'period', 'tier'],
                'constraints': [models.UniqueConstraint(fields=('season', 'period', 'tier', 'effective_from'), name='uniq_utility_rate')],
            },
        ),
    ]
