# Generated by Django 5.2.17 on 2026-08-04 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('solar', 'Solar'), ('grid', 'Grid'), ('ev', 'Ev')], max_length=20)),
                ('poll_interval_s', models.PositiveIntegerField()),
                ('native_resolution_s', models.PositiveIntegerField()),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=10)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='core.source')),
            ],
            options={
                'verbose_name_plural': 'series',
            },
        ),
        migrations.CreateModel(
            name='CollectorRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField()),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('ok', models.BooleanField(null=True)),
                ('message', models.TextField(blank=True, default='')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='core.source')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField()),
                ('duration_s', models.PositiveIntegerField()),
                ('value', models.FloatField()),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='core.series')),
            ],
            options={
                'indexes': [models.Index(fields=['series', 'ts'], name='idx_sample_series_ts')],
                'constraints': [models.UniqueConstraint(fields=('series', 'ts'), name='uniq_sample')],
            },
        ),
        migrations.CreateModel(
            name='CoverageSpan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('state', models.CharField(choices=[('live', 'Live'), ('backfilled', 'Backfilled'), ('confirmed_empty', 'Confirmed Empty')], max_length=20)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage', to='core.series')),
            ],
            options={
                'indexes': [models.Index(fields=['series', 'start'], name='idx_cov_series_start')],
            },
        ),
        migrations.AddConstraint(
            model_name='series',
            constraint=models.UniqueConstraint(fields=('source', 'metric'), name='uniq_series'),
        ),
        migrations.AddIndex(
            model_name='collectorrun',
            index=models.Index(fields=['source', '-started'], name='idx_run_source_started'),
        ),
    ]
