# Generated by Django 5.2.17 on 2026-10-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='kind',
            field=models.CharField(choices=[('solar', 'Solar'), ('grid', 'Grid'), ('ev', 'Ev'), ('gas', 'Gas')], max_length=20),
        ),
    ]
