# Generated by Django 5.2.17 on 2026-10-06 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_seed_milestones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='kind',
            field=models.CharField(choices=[('solar', 'Solar'), ('grid', 'Grid'), ('ev', 'Ev'), ('gas', 'Gas'), ('device', 'Device')], max_length=20),
        ),
    ]
