# Generated by Django 5.2.17 on 2026-10-09 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_source_kind_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='kind',
            field=models.CharField(choices=[('solar', 'Solar'), ('grid', 'Grid'), ('ev', 'Ev'), ('gas', 'Gas'), ('device', 'Device'), ('estimate', 'Estimate')], max_length=20),
        ),
    ]
